# Generated by Django 5.2 on 2025-05-06 04:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_project_image_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='resume'),
        ),
    ]
